name: Deploy via Vercel Hook

on:
  push:
    branches:
      - main

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel Deploy Hook
        env:
          VERCEL_DEPLOY_HOOK_URL: ${{ secrets.VERCEL_DEPLOY_HOOK_URL }}
        run: |
          if [ -z "$VERCEL_DEPLOY_HOOK_URL" ]; then
            echo "::error::Missing secret VERCEL_DEPLOY_HOOK_URL" && exit 1
          fi
          curl -fsS -X POST "$VERCEL_DEPLOY_HOOK_URL"

